
name: プルリクエスト用ビルドチェック

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - uses: actions/checkout@v4
    - name: Javaセットアップ JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Mavenビルド
      run: mvn -B package --file pom.xml
    - name: ビルド成果物のアップロード
      run: |
        mkdir staging
        cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: staging
